In [1]:
import pandas as pd
import numpy as np


In [2]:
data=pd.read_csv("spam.csv", encoding="latin-1")

In [3]:
data.head()

class                                            message Unnamed: 2  \
0   ham  Go until jurong point, crazy.. Available only ...        NaN   
1   ham                      Ok lar... Joking wif u oni...        NaN   
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3   ham  U dun say so early hor... U c already then say...        NaN   
4   ham  Nah I don't think he goes to usf, he lives aro...        NaN   

  Unnamed: 3 Unnamed: 4  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN

In [4]:
data.columns

Index(['class', 'message', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'], dtype='object')

In [5]:
data.drop(['Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'], axis=1, inplace=True)

In [6]:
data.head()

class                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [7]:
data['class']=data['class'].map({'ham':0, 'spam':1})

In [8]:
data.head()

class                                            message
0      0  Go until jurong point, crazy.. Available only ...
1      0                      Ok lar... Joking wif u oni...
2      1  Free entry in 2 a wkly comp to win FA Cup fina...
3      0  U dun say so early hor... U c already then say...
4      0  Nah I don't think he goes to usf, he lives aro...

In [9]:
from sklearn.feature_extraction.text import CountVectorizer

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
X=data['message']
y=data['class']

In [12]:
X.shape

(5572,)

In [13]:
y.shape

(5572,)

In [14]:
data.isnull().sum()

class      0
message    0
dtype: int64

In [15]:
cv=CountVectorizer()

In [16]:
X=cv.fit_transform(X)

In [17]:
x_train, x_test,y_train, y_test=train_test_split(X,y, test_size=0.2, random_state=42)

In [18]:
x_train.shape

(4457, 8672)

In [19]:
x_test.shape

(1115, 8672)

In [20]:
from sklearn.naive_bayes import MultinomialNB

In [21]:
model=MultinomialNB()

In [22]:
model.fit(x_train, y_train)

MultinomialNB()

In [23]:
model.score(x_test, y_test)

0.97847533632287

In [24]:
msg="You Won 500$"
data = [msg]
vect = cv.transform(data).toarray()
my_prediction = model.predict(vect)

In [25]:
vect

array([[0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [26]:
import pickle
pickle.dump(model, open('spam.pkl','wb'))
model1 = pickle.load(open('spam.pkl','rb'))


In [27]:
import pickle
pickle.dump(cv, open('vec.pkl','wb'))
#model1 = pickle.load(open('spam.pkl','rb'))

In [28]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split

# Reload the dataset if necessary
data = pd.read_csv("spam.csv", encoding="latin-1")
data.drop(['Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'], axis=1, inplace=True)
data.rename(columns={'v1': 'class', 'v2': 'message'}, inplace=True)

# Map target variable
data['class'] = data['class'].map({'ham': 0, 'spam': 1})

# Preprocess and vectorize
tfidf = TfidfVectorizer(stop_words='english', max_features=5000)
X_tfidf = tfidf.fit_transform(data['message'])  # Ensure 'message' column exists
y = data['class']

# Split the data
x_train, x_test, y_train, y_test = train_test_split(X_tfidf, y, test_size=0.2, random_state=42)


In [29]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
import pickle

# Load dataset
data = pd.read_csv("spam.csv", encoding="latin-1")
data.drop(['Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'], axis=1, inplace=True)
data.rename(columns={'v1': 'class', 'v2': 'message'}, inplace=True)
data['class'] = data['class'].map({'ham': 0, 'spam': 1})

# Preprocess data
X = data['message']
y = data['class']
vectorizer = TfidfVectorizer(stop_words='english', max_features=5000)
X = vectorizer.fit_transform(X)

# Split data
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Function to train and evaluate models
def train_and_evaluate_model(model, model_name):
    print(f"Training {model_name}...")
    model.fit(x_train, y_train)
    predictions = model.predict(x_test)
    print(f"Results for {model_name}:")
    print("Accuracy:", accuracy_score(y_test, predictions))
    print("Confusion Matrix:\n", confusion_matrix(y_test, predictions))
    print("Classification Report:\n", classification_report(y_test, predictions))
    print("-" * 60)
    # Save the model
    with open(f"{model_name}.pkl", 'wb') as f:
        pickle.dump(model, f)

# Naive Bayes
nb_model = MultinomialNB()
train_and_evaluate_model(nb_model, "Naive_Bayes")

# Support Vector Machine
svm_model = SVC(kernel='linear', probability=True)
train_and_evaluate_model(svm_model, "SVM")

# Decision Tree
dt_model = DecisionTreeClassifier(random_state=42)
train_and_evaluate_model(dt_model, "Decision_Tree")

# Random Forest
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
train_and_evaluate_model(rf_model, "Random_Forest")

# Neural Network
nn_model = MLPClassifier(hidden_layer_sizes=(100,), max_iter=300, random_state=42)
train_and_evaluate_model(nn_model, "Neural_Network")

# Save the vectorizer
with open("vectorizer.pkl", 'wb') as f:
    pickle.dump(vectorizer, f)


Training Naive_Bayes...
Results for Naive_Bayes:
Accuracy: 0.9757847533632287
Confusion Matrix:
 [[965   0]
 [ 27 123]]
Classification Report:
               precision    recall  f1-score   support

           0       0.97      1.00      0.99       965
           1       1.00      0.82      0.90       150

    accuracy                           0.98      1115
   macro avg       0.99      0.91      0.94      1115
weighted avg       0.98      0.98      0.97      1115

------------------------------------------------------------
Training SVM...
Results for SVM:
Accuracy: 0.9757847533632287
Confusion Matrix:
 [[961   4]
 [ 23 127]]
Classification Report:
               precision    recall  f1-score   support

           0       0.98      1.00      0.99       965
           1       0.97      0.85      0.90       150

    accuracy                           0.98      1115
   macro avg       0.97      0.92      0.95      1115
weighted avg       0.98      0.98      0.98      1115

-------------